---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Domain:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone
    AllowedPattern: "(?!-)[a-zA-Z0-9-.]{1,63}(?<!-)"
    ConstraintDescription: must be a valid DNS zone name.
Resources:
  TasksHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        HostedZoneConfig
      Name:
        Ref: Domain
  VueAppS3Policy:  # new
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Fn::ImportValue: s3-development-tasks-api-ielegante-name
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            Action: "s3:GetObject"
            Resource:
              Fn::Join:
                - '/'
                - - Fn::ImportValue: s3-development-tasks-api-ielegante-arn
                  - '*'
  APICachePolicy:  # new
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        DefaultTTL: 0
        MaxTTL: 1
        MinTTL: 0
        Name: APICachePolicy
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: all
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - Authorization
              - Content-Type
          QueryStringsConfig:
            QueryStringBehavior: none
  VueAppCachePolicy:  # new
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        DefaultTTL: 30
        MaxTTL: 60
        MinTTL: 0
        Name: VueAppCachePolicy
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: all
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - Content-Type
          QueryStringsConfig:
            QueryStringBehavior: none
  TasksCloudFront:  # new
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName:
              Fn::Join:
                - '.'
                - - Fn::ImportValue: s3-development-tasks-api-ielegante-name
                  - 's3.amazonaws.com'
            Id: vueApp
            S3OriginConfig:
              OriginAccessIdentity:
                  Fn::Join:
                      - ''
                      -
                        - 'origin-access-identity/cloudfront/'
                        - Ref: CloudFrontOriginAccessIdentity
          - DomainName: https://ytjyf6do4b.execute-api.eu-west-1.amazonaws.com/development/api
            Id: api
            OriginPath: /development
            CustomOriginConfig:
              HTTPSPort: '443'
              OriginProtocolPolicy: https-only
        Enabled: 'true'
        DefaultRootObject: index.html
        Aliases:
          - Ref: Domain
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          TargetOriginId: vueApp
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId:
            Ref: VueAppCachePolicy
        CacheBehaviors:
          - AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
            CachePolicyId:
              Ref: APICachePolicy
            PathPattern: api/*
            TargetOriginId: api
            ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:989757409235:certificate/ad59ba89-e418-4639-9105-8a860e084b8b
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
  CloudFrontDNSRecord:  # new
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt TasksCloudFront.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # See docs for more details https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
      HostedZoneId:
        Ref: TasksHostedZone
      Name:
        Ref: Domain
      Type: A
Outputs:
  HostedZoneId:
    Description: Hosted zone ID
    Value:
      Ref: TasksHostedZone
# Output the CloudFront distribution domain name
  DistributionDomainName:
    Description: The CloudFront distribution domain name
    Value:
      Fn::GetAtt:
        - TasksCloudFront
        - DomainName
```
  